---
name: helloworld
cpu_limit: 0.5 # global set to all containers
memory_limit: 100M # global set to all containers
resource_thresholds:
  cpu_percentage: 80 # Threshold for CPU percent
  cpu_percentage_relative: 30 # Threshold for CPU perc relative to the cpu_limit
  memory_percentage: 30 # Threshold for memory utilisation percentage.
instance_count:
  min: 1 # Number of instances to spawn at start.
  max: 10 # Maximum number of instances allowed.
pull_policy: Always # autorize pulling of image
spec:
  containers:
  - name: main
    image: nginx:latest
    ports:
    - port: 80
      node_port: 4333
