name: helloworld2
cpu_limit: 0.5 # global set to all containers
memory_limit: 100M # global set to all containers
resource_thresholds:
  cpu_percentage: 80 # Threshold for CPU percent
  cpu_percentage_relative: 30 # Threshold for CPU perc relative to the cpu_limit
  memory_percentage: 30 # Threshold for memory utilisation percentage.
instance_count:
  min: 2 # Number of instances to spawn at start.
  max: 10 # Maximum number of instances allowed.
spec:
  containers:
    - name: main
      image: airpipeio/infoapp:latest
      ports:
        - port: 80
    - name: nginx-sidecar
      image: nginx:latest
      memory_limit: 200M
      ports:
        - port: 8080
          node_port: 4335
      volume_mounts:
        - name: nginx-config
          mount_path: /etc/nginx/nginx.conf
          sub_path: nginx.conf
volumes:
  nginx-config:
    files:
      nginx.conf: |-
        events {}
        http {
            server {
                listen 8080;
                location / {
                    proxy_pass http://helloworld2-main:80;
                }
            }
        }
