name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: linux
            arch: amd64
          - target: aarch64-unknown-linux-gnu
            os: linux
            arch: arm64
          - target: aarch64-apple-darwin
            os: darwin
            arch: arm64

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cross-compilation dependencies
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: ${{ matrix.target != 'x86_64-unknown-linux-gnu' }}

      - name: Package Binary
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../orbit-${{ matrix.os }}-${{ matrix.arch }}.tar.gz orbit
          cd ../../..

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: orbit-${{ matrix.os }}-${{ matrix.arch }}
          path: orbit-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            orbit-linux-amd64/orbit-linux-amd64.tar.gz
            orbit-linux-arm64/orbit-linux-arm64.tar.gz
            orbit-darwin-arm64/orbit-darwin-arm64.tar.gz